### ISSUE TITLE
Format Python Launch files to meet style guidelines

### ISSUE THREAD

**Issue by andyblarblar** [iscumd/Mammoth#58]
It looks like the Ros2 github action is failing because a linter is set up to err on style guidelines not being followed. We should really make a pipeline that formats our code on CI run, else the CI will always fail even if the tests pass, which Isn't very useful.

**Comment by girvenavery2022** [comment]
Correct, I have just had way to much to do and its kinda an annoyance to fix as of now (bad I know). I really like the idea of adding in a pipeline that formats the code on CI run because I do want to ensure the entire project follows the same coding style. if you'd make a PR with the change, I will for sure merge it into ros2 branch.
